### ISSUE TITLE
Change the name of "Ister Cloud Init Sv" to "Clear Cloud Init Svc"

### ISSUE THREAD

**Issue by bktan8** [clearlinux/ister-cloud-init-svc#9]
Since we will be deprecating Ister from the Clear PXE image and using clr-installer instead, I think it is appropriate to change the name of ICIS.

**Comment by mdhorn** [comment]
@ahkok Are you okay with this change?  Are you the right person with the authority to make the modification?
We just made a new release or the clr-installer which enabled PXE support. The next Clear Linux OS release will have a new pxe image that invokes clr-installer instead of ister.

**Comment by ahkok** [comment]
Consider it done.

**Comment by ahkok** [comment]
Actually

`"Clear Cloud Init Svc"` Is not a valid github name. We can't use spaces, nor does it match how we use the project name in any project.

Do you want `clr-cloud-init-svc` or `clear-cloud-init-svc`. My preference would be the first.

**Comment by mdhorn** [comment]
> Actually
> 
> `"Clear Cloud Init Svc"` Is not a valid github name. We can't use spaces, nor does it match how we use the project name in any project.
> 
> Do you want `clr-cloud-init-svc` or `clear-cloud-init-svc`. My preference would be the first.

The first option is more consistent with our other names.

**Comment by ahkok** [comment]
Done

**Comment by mdhorn** [comment]
> Done

Thank you! 👍
